# -*- coding: utf-8 -*-
"""Copy of Shadab Sharif Student_FakeNews_Section3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VKPjuEtpWzs9yWrmhtpmyktHYDqoRMI


"""

#@title Import Data { display-mode: "form" }
import math
import os
import numpy as np
from bs4 import BeautifulSoup as bs
import requests
from tqdm import tqdm
from sklearn.feature_extraction.text import CountVectorizer
from torchtext.vocab import GloVe

import pickle

import requests, io, zipfile
!wget -O data.zip 'https://storage.googleapis.com/inspirit-ai-data-bucket-1/Data/AI%20Scholars/Sessions%206%20-%2010%20(Projects)/Project%20-%20Fake%20News%20Detection/inspirit_fake_news_resources%20(1).zip'
!unzip data.zip

basepath = '.'

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

with open(os.path.join(basepath, 'train_val_data.pkl'), 'rb') as f:
  train_data, val_data = pickle.load(f)

print('Number of train examples:', len(train_data))
print('Number of val examples:', len(val_data))


def get_description_from_html(html):
  soup = bs(html)
  description_tag = soup.find('meta', attrs={'name':'og:description'}) or soup.find('meta', attrs={'property':'description'}) or soup.find('meta', attrs={'name':'description'})
  if description_tag:
    description = description_tag.get('content') or ''
  else: # If there is no description, return empty string.
    description = ''
  return description

def scrape_description(url):
  if not url.startswith('http'):
    url = 'http://' + url
  try:
    response = requests.get(url, timeout=30)
  except requests.exceptions.RequestException as e:
    print(f"Error fetching {url}: {e}")
    return ""
  html = response.text
  description = get_description_from_html(html)
  return description

print('Description of Google.com:')
print(scrape_description('google.com'))


#@title Live Website Description Scraper { display-mode: "both" }

url = "spotify.com" #@param {type:"string"}

print('Description of %s:' % url)
print(scrape_description(url))


def get_descriptions_from_data(data):
  # A dictionary mapping from url to description for the websites in
  # train_data.
  descriptions = []
  for site in tqdm(data):
    description = scrape_description(site[0])
    descriptions.append(description)
  return descriptions

train_descriptions = get_descriptions_from_data(train_data)
train_urls = [url for (url, html, label) in train_data]

print('\nNYTimes Description:')
print(train_descriptions[train_urls.index('nytimes.com')])


val_descriptions = get_descriptions_from_data(val_data)


vectorizer = CountVectorizer(max_features=300)

vectorizer.fit(train_descriptions)

def vectorize_data_descriptions(descriptions, vectorizer):
  X = vectorizer.transform(descriptions).todense()
  return X

print('\nPreparing train data...')
bow_X_train = vectorize_data_descriptions(train_descriptions, vectorizer)
bow_y_train = [label for url, html, label in train_data]

print('\nPreparing val data...')

bow_X_val = vectorize_data_descriptions(val_descriptions, vectorizer)
bow_y_val = [label for url, html, label in val_data]



model = LogisticRegression()

model.fit(bow_X_train, bow_y_train)

# Predict train and validation set labels
train_preds = model.predict(bow_X_train)
val_preds = model.predict(bow_X_val)

# Calculate train and validation accuracies
train_acc = accuracy_score(bow_y_train, train_preds)
val_acc = accuracy_score(bow_y_val, val_preds)

# Calculate validation confusion matrix
val_cm = confusion_matrix(bow_y_val, val_preds)

# Calculate validation precision, recall, and F1 score
val_precision, val_recall, val_f1score, _ = precision_recall_fscore_support(bow_y_val, val_preds, average='binary')

print("Train accuracy:", train_acc)
print("Validation accuracy:", val_acc)
print("Validation confusion matrix:\n", val_cm)
print("Validation precision:", val_precision)
print("Validation recall:", val_recall)
print("Validation F1-Score:", val_f1score)


VEC_SIZE = 300
glove = GloVe(name='6B', dim=VEC_SIZE)

# Returns word vector for word if it exists, else return None.
def get_word_vector(word):
    try:
      return glove.vectors[glove.stoi[word.lower()]].numpy()
    except KeyError:
      return None


### YOUR CODE HERE ###
good_vector = get_word_vector("good")
### END CODE HERE ###

print('Shape of good vector:', good_vector.shape)
print(good_vector)


#@title Word Similarity { run: "auto", display-mode: "both" }

def cosine_similarity(vec1, vec2):
  return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

word1 = "good" #@param {type:"string"}
word2 = "great" #@param {type:"string"}

print('Word 1:', word1)
print('Word 2:', word2)

def cosine_similarity_of_words(word1, word2):
  vec1 = get_word_vector(word1)
  vec2 = get_word_vector(word2)

  if vec1 is None:
    print(word1, 'is not a valid word. Try another.')
  if vec2 is None:
    print(word2, 'is not a valid word. Try another.')
  if vec1 is None or vec2 is None:
    return None

  return cosine_similarity(vec1, vec2)


print('\nCosine similarity:', cosine_similarity_of_words(word1, word2))


def glove_transform_data_descriptions(descriptions):
    X = np.zeros((len(descriptions), VEC_SIZE))
    for i, description in enumerate(descriptions):
        found_words = 0.0
        description = description.strip()
        for word in description.split():
            vec = get_word_vector(word)
            if vec is not None:
                ### YOUR CODE HERE ###
                # Increment found_words and add vec to X[i].
                found_words += 1
                X[i] += vec

                ### END CODE HERE ###
        # We divide the sum by the number of words added, so we have the
        # average word vector.
        if found_words > 0:
            X[i] /= found_words

    return X

glove_X_train = glove_transform_data_descriptions(train_descriptions)
glove_y_train = [label for (url, html, label) in train_data]

glove_X_val = glove_transform_data_descriptions(val_descriptions)
glove_y_val = [label for (url, html, label) in val_data]


model = LogisticRegression()
### YOUR CODE HERE ###
model.fit(glove_X_train, glove_y_train)

# Predict train and validation set labels
train_preds = model.predict(glove_X_train)
val_preds = model.predict(glove_X_val)

# Calculate train and validation accuracies
train_acc = accuracy_score(glove_y_train, train_preds)
val_acc = accuracy_score(glove_y_val, val_preds)

# Calculate validation confusion matrix
val_cm = confusion_matrix(glove_y_val, val_preds)

# Calculate validation precision, recall, and F1 score
val_precision, val_recall, val_f1score, _ = precision_recall_fscore_support(bow_y_val, val_preds, average='binary')

print("Train accuracy:", train_acc)
print("Validation accuracy:", val_acc)
print("Validation confusion matrix:\n", val_cm)
print("Validation precision:", val_precision)
print("Validation recall:", val_recall)
print("Validation F1-Score:", val_f1score)
### END CODE HERE ###

def train_model(X_train, y_train, X_val, y_val):
  model = LogisticRegression(solver='liblinear')
  model.fit(X_train, y_train)

  return model


def train_and_evaluate_model(X_train, y_train, X_val, y_val):
  model = train_model(X_train, y_train, X_val, y_val)

    # Make predictions on train and validation sets
  train_preds = model.predict(X_train)
  val_preds = model.predict(X_val)

    # Calculate evaluation metrics
  train_acc = accuracy_score(y_train, train_preds)
  val_acc = accuracy_score(y_val, val_preds)
  cm = confusion_matrix(y_val, val_preds)
  precision = precision_score(y_val, val_preds)
  recall = recall_score(y_val, val_preds)
  f1 = f1_score(y_val, val_preds)

  # Print evaluation metrics
  print("Train accuracy:", train_acc)
  print("Validation accuracy:", val_acc)
  print("Confusion matrix:\n", cm)
  print("Precision:", precision)
  print("Recall:", recall)
  print("F1-score:", f1)

  return model


def prepare_data(data, featurizer):
    X = []
    y = []
    for datapoint in data:
        url, html, label = datapoint
        # We convert all text in HTML to lowercase, so <p>Hello.</p> is mapped to
        # <p>hello</p>. This will help us later when we extract features from
        # the HTML, as we will be able to rely on the HTML being lowercase.
        html = html.lower()
        y.append(label)

        features = featurizer(url, html)

        # Gets the keys of the dictionary as descriptions, gets the values
        # as the numerical features. Don't worry about exactly what zip does!
        feature_descriptions, feature_values = zip(*features.items())

        X.append(feature_values)

    return X, y, feature_descriptions

# Gets the log count of a phrase/keyword in HTML (transforming the phrase/keyword
# to lowercase).
def get_normalized_count(html, phrase):
    return math.log(1 + html.count(phrase.lower()))

# Returns a dictionary mapping from plaintext feature descriptions to numerical
# features for a (url, html) pair.
def keyword_featurizer(url, html):
    features = {}

    # Same as before.
    features['.com domain'] = url.endswith('.com')
    features['.org domain'] = url.endswith('.org')
    features['.net domain'] = url.endswith('.net')
    features['.info domain'] = url.endswith('.info')
    features['.org domain'] = url.endswith('.org')
    features['.biz domain'] = url.endswith('.biz')
    features['.ru domain'] = url.endswith('.ru')
    features['.co.uk domain'] = url.endswith('.co.uk')
    features['.co domain'] = url.endswith('.co')
    features['.tv domain'] = url.endswith('.tv')
    features['.news domain'] = url.endswith('.news')

    keywords = ['trump', 'biden', 'clinton', 'sports', 'finance']

    for keyword in keywords:
      features[keyword + ' keyword'] = get_normalized_count(html, keyword)

    return features



data = load_data(train_data)

# Split the data into training and validation sets
train_data, val_data = split_data(data)

# Prepare the data using the keyword featurizer
X_train, y_train, feature_descriptions = prepare_data(train_data, keyword_featurizer)
X_val, y_val, _ = prepare_data(val_data, keyword_featurizer)

# Train and evaluate the model
model = train_and_evaluate_model(X_train, y_train, X_val, y_val)



vectorizer = CountVectorizer(max_features=300)

vectorizer.fit(train_descriptions)

def vectorize_data_descriptions(data_descriptions, vectorizer):
  X = vectorizer.transform(data_descriptions).todense()
  return X



VEC_SIZE = 300
glove = GloVe(name='6B', dim=VEC_SIZE)

# Returns word vector for word if it exists, else return None.
def get_word_vector(word):
    try:
      return glove.vectors[glove.stoi[word.lower()]].numpy()
    except KeyError:
      return None

def glove_transform_data_descriptions(descriptions):
    X = np.zeros((len(descriptions), VEC_SIZE))
    for i, description in enumerate(descriptions):
        found_words = 0.0
        description = description.strip()
        for word in description.split():
            vec = get_word_vector(word)
            if vec is not None:
                ### YOUR CODE HERE ###
                # Increment found_words and add vec to X[i].
                found_words += 1
                X[i] += vec
                ### END CODE HERE ###
        # We divide the sum by the number of words added, so we have the
        # average word vector.
        if found_words > 0:
            X[i] /= found_words

    return X



def combine_features(X_list):
  return np.concatenate(X_list, axis=1)


#@title Live Fake News Classification Demo { run: "auto", vertical-output: true, display-mode: "both" }
def get_data_pair(url):
  if not url.startswith('http'):
      url = 'http://' + url
  url_pretty = url
  if url_pretty.startswith('http://'):
      url_pretty = url_pretty[7:]
  if url_pretty.startswith('https://'):
      url_pretty = url_pretty[8:]

  # Scrape website for HTML
  response = requests.get(url, timeout=10)
  htmltext = response.text

  return url_pretty, htmltext

curr_url = "www.yahoo.com" #@param {type:"string"}

url, html = get_data_pair(curr_url)

# Call on the output of *keyword_featurizer* or something similar
# to transform it into a format that allows for concatenation.
def dict_to_features(features_dict):
  X = np.array(list(features_dict.values())).astype('float')
  X = X[np.newaxis, :]
  return X
def featurize_data_pair(url, html):
  # Approach 1.
  keyword_X = dict_to_features(keyword_featurizer(url, html))
  # Approach 2.
  description = get_description_from_html(html)

  bow_X = vectorize_data_descriptions([description], vectorizer)

  # Approach 3.
  glove_X = glove_transform_data_descriptions([description])

  X = combine_features([keyword_X, bow_X, glove_X])

  return X

curr_X = featurize_data_pair(url, html)

model = train_model(combined_X_train, y_train, combined_X_val, y_val)

curr_y = model.predict(curr_X)[0]


if curr_y < .5:
  print(curr_url, 'appears to be real.')
else:
  print(curr_url, 'appears to be fake.')

